### PR TITLE
Fix Typos again

### PR DESCRIPTION
**Pull request by chrollorifat**

### CODE REVIEW

**Comment by dharmx** [comment]
Thank you!

**Comment by chrollorifat** [comment]
> Thank you!

No need to thank anymore, bro. I love widgets and the repo.

**Comment by dharmx** [comment]
Thank you!

> No need to thank anymore, bro. I love widgets and the repo.

Haha I can't do that man.

Its kind of embarrassing that I made this many typos.

**Comment by chrollorifat** [comment]
no need to feel embarrased, man. It happens, especially when projects are such well documented.

**Pull request merged**
